include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    - camel_case_types
    - library_names
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - unnecessary_brace_in_string_interps
    - avoid_redundant_argument_values
    - leading_newlines_in_multiline_strings
    # formatting
    - always_use_package_imports
    - require_trailing_commas
    - curly_braces_in_flow_control_structures
    # doc comments
    - slash_for_doc_comments
    - avoid_print  # Uncomment to disable the `avoid_print` rule
    - prefer_single_quotes  # Uncomment to enable the `prefer_single_quotes` rule

